path: data/bdd100k
train: 
- train
validation: val

class_num: 13
class_list: ['pedestrian', 'rider', 'car', 'bus', 'truck', 'bicycle', 'motorcycle', 'traffic light', 'traffic sign', 'train', 'trailer', 'other person', 'other vehicle']

auto_download:
