path: data/voc
train:
- train2007
- val2007
- train2012
- val2007
validation: test2007

class_num: 20
class_list: ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']

auto_download:
